In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,99)

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [8]:
a = np.array([12,9,62,30,0])
a

array([12,  9, 62, 30,  0])

In [10]:
a[2] = 90

In [11]:
a

array([12,  9, 90, 30,  0])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n[0,1] = 20

In [20]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [21]:
n[0]

array([ 1, 20,  3])

In [22]:
n[1]

array([4, 5, 6])

In [23]:
n[2] = np.ones(3)

In [24]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [25]:
n[:,1]

array([20,  5,  1])

In [27]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [30]:
np.random.seed(2)
np.random.randint(low=0, high = 100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [37]:

b = (10 + (a * 2)) ** 2 / 100

In [39]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [40]:
a

array([0, 1, 2, 3, 4])

In [41]:
a >= 2

array([False, False,  True,  True,  True])

In [42]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [43]:
a > b 

array([False, False,  True,  True,  True])

In [44]:
a[a>b]

array([2, 3, 4])

In [45]:
a.min()

np.int64(0)

In [46]:
a.max()

np.int64(4)

In [47]:
a.mean()

np.float64(2.0)

In [48]:
a.std()

np.float64(1.4142135623730951)

In [49]:
a.sum()

np.int64(10)

In [50]:
n.sum()

np.int64(42)

In [51]:
n.min()

np.int64(1)